version: '3'

services:
  ts-node-docker:
    environment:
      - NODE_ENV=production
      - GOTENBERG_URL=http://gotenberg:3000  # Add this environment variable
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: node dist/index.js
