version: '3'

services:
  gotenberg:
    image: gotenberg/gotenberg:8.7.0
    ports:
      - 3000:3000

  ts-node-docker:
    environment:
      - NODE_ENV=production
      - GOTENBERG_URL=http://gotenberg:3000  # Add this environment variable
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - gotenberg
    command: node dist/index.js
